import { useState } from "react";
import AppSidebar from "@/components/AppSidebar";
import TopBar from "@/components/TopBar";
import { FileText, Download, Loader2, Brain } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useFloodZones, useDrainageSegments, useFloodAlerts, useWeatherReadings } from "@/hooks/useFloodData";
import { toast } from "sonner";
import PopulationPanel from "@/components/PopulationPanel";
import HistoricalRainfall from "@/components/HistoricalRainfall";

const monoFont = { fontFamily: "'JetBrains Mono', monospace" };

const ReportsPage = () => {
  const { data: zones = [] } = useFloodZones();
  const { data: drains = [] } = useDrainageSegments();
  const { data: alerts = [] } = useFloodAlerts();
  const { data: weather = [] } = useWeatherReadings();
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState<string | null>(null);

  const generateReport = async () => {
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("flood-predict", {
        body: {},
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      const reportText = `
# FloodGuard AI Report — ${new Date().toLocaleString()}
## Kadapa Flood Risk Assessment

### Overall Risk: ${data.overall_risk_score}/100 (${data.risk_level?.toUpperCase()})
**Confidence:** ${(data.confidence * 100).toFixed(0)}%

### Summary
${data.summary}

### Zone Analysis
${data.zone_predictions?.map((z: any) => `- **${z.zone_name}**: ${z.predicted_risk}% risk (${z.trend}) — ${z.reasoning}`).join("\n") ?? "No zone predictions"}

### Recommendations
${data.recommendations?.map((r: string, i: number) => `${i + 1}. ${r}`).join("\n") ?? "None"}

### 6-Hour Forecast
${data.six_hour_forecast}

---
*Generated by FloodGuard AI · Gemini 3 Flash*
*Data: ${zones.length} flood zones · ${drains.length} drainage segments · ${alerts.length} active alerts · ${weather.length} weather readings*
      `.trim();

      setReport(reportText);
      toast.success("Report generated");
    } catch (err: any) {
      toast.error(err.message || "Report generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const downloadReport = () => {
    if (!report) return;
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `floodguard-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex min-h-screen bg-background">
      <AppSidebar />
      <div className="flex-1 flex flex-col min-h-screen overflow-hidden">
        <TopBar />
        <main className="flex-1 p-4 space-y-4 overflow-y-auto">
          <div className="glass-panel p-4">
            <h3 className="text-sm font-semibold text-foreground tracking-wide mb-2" style={monoFont}>AI-GENERATED REPORTS</h3>
            <p className="text-xs text-muted-foreground">
              Generate comprehensive flood risk reports using AI analysis of real-time data
            </p>
          </div>

          <div className="glass-panel p-4 flex items-center gap-4">
            <button
              onClick={generateReport}
              disabled={generating}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary/20 text-primary hover:bg-primary/30 border border-primary/30 transition-all disabled:opacity-50 text-xs font-semibold"
              style={monoFont}
            >
              {generating ? <Loader2 size={14} className="animate-spin" /> : <Brain size={14} />}
              {generating ? "GENERATING..." : "GENERATE AI REPORT"}
            </button>
            {report && (
              <button
                onClick={downloadReport}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-secondary text-foreground hover:bg-secondary/80 transition-all text-xs font-semibold"
                style={monoFont}
              >
                <Download size={14} />
                DOWNLOAD MD
              </button>
            )}
          </div>

          {/* Data Summary */}
          {(() => {
            const activeZones = zones.filter(z => z.risk === "critical" || z.risk === "high").length;
            const criticalZones = zones.filter(z => z.risk === "critical").length;
            const criticalAlerts = alerts.filter(a => a.severity === "critical").length;
            return (
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                <div className="glass-panel p-3">
                  <p className="text-[10px] text-muted-foreground uppercase" style={monoFont}>Active Flood Zones</p>
                  <p className="text-2xl font-bold text-foreground" style={monoFont}>{activeZones}</p>
                  <p className="text-[10px] text-muted-foreground" style={monoFont}>{criticalZones} critical · {zones.length} total</p>
                </div>
                <div className="glass-panel p-3">
                  <p className="text-[10px] text-muted-foreground uppercase" style={monoFont}>Drainage Segments</p>
                  <p className="text-2xl font-bold text-foreground" style={monoFont}>{drains.length}</p>
                  <p className="text-[10px] text-muted-foreground" style={monoFont}>Monitored network</p>
                </div>
                <div className="glass-panel p-3">
                  <p className="text-[10px] text-muted-foreground uppercase" style={monoFont}>Active Alerts</p>
                  <p className="text-2xl font-bold text-foreground" style={monoFont}>{alerts.length}</p>
                  <p className="text-[10px] text-muted-foreground" style={monoFont}>{criticalAlerts} critical</p>
                </div>
                <div className="glass-panel p-3">
                  <p className="text-[10px] text-muted-foreground uppercase" style={monoFont}>Weather Readings</p>
                  <p className="text-2xl font-bold text-foreground" style={monoFont}>{weather.length}</p>
                  <p className="text-[10px] text-muted-foreground" style={monoFont}>Live data points</p>
                </div>
              </div>
            );
          })()}

          {/* Report Content */}
          {report && (
            <div className="glass-panel p-6 animate-fade-in">
              <pre className="text-xs text-foreground/80 whitespace-pre-wrap leading-relaxed font-sans">
                {report}
              </pre>
            </div>
          )}

          {/* CSV Data Sections */}
          <PopulationPanel compact />
          <HistoricalRainfall />
        </main>
      </div>
    </div>
  );
};

export default ReportsPage;
